kind: ConfigMap
apiVersion: v1
metadata:
  annotations: {}
  name: fluentd-config
  namespace: kube-logging
data:
  fluent.conf: |
    <match ***>
      @type elasticsearch
      host elasticsearch.kube-logging.svc.cluster.local
      port 9200
      index_name fluentd
    </match>
